config/routes.rb
Rails.application.routes.draw do
  resources :contents, except: [:show, :update, :destroy]
  resources :contents, path: 'conteudo', only: [:show, :update, :destroy]

  resources :domains

  constraints SubdomainConstraint do
    get '', to: 'domains#show'
  end

  root 'home#index'

end

app/models/content.rb
class Content < ActiveRecord::Base
  belongs_to :domain

  before_save :update_slug

  protected

  def update_slug
    self.slug = self.title.parameterize
  end
end

app/models/domain.rb
class Domain < ActiveRecord::Base
  has_many :contents

  def has_page_domain?
    self.description?
  end
end

app/models/subdomain_constraint.rb
# Checks the presence of a subdomain and its difference from `www`
class SubdomainConstraint
  def self.matches?(request)
    request.subdomain.present? && request.subdomain != 'www'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_logger

  private

  def set_logger
    logger.debug "Subdomain >> #{request.subdomain}"
  end

  def load_subdomain
    @current_subdomain = Domain.find_by!(subdomain: request.subdomain)
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :load_subdomain, except: [:index]
  before_action :set_content, only: [:show, :edit, :update, :destroy]

  def index
    @contents = Content.all
  end

  def show
  end

  def new
    @content = Content.new
  end

  def edit
  end

  def create
    @content = Content.new(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, notice: 'Content was successfully created.' }
        format.json { render :show, status: :created, location: @content }
      else
        format.html { render :new }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to @content, notice: 'Content was successfully updated.' }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_url, notice: 'Content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_content
    @content = @current_subdomain.contents.find(params[:id])
  end

  def content_params
    params.require(:content).permit(:domain_id, :title, :slug, :description)
  end
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  before_action :set_domain, only: [:show, :edit, :update, :destroy]

  def index
    @domains = Domain.all
  end

  def show
  end

  def new
    @domain = Domain.new
  end

  def edit
  end

  def create
    @domain = Domain.new(domain_params)

    respond_to do |format|
      if @domain.save
        format.html { redirect_to @domain, notice: 'Domain was successfully created.' }
        format.json { render :show, status: :created, location: @domain }
      else
        format.html { render :new }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @domain.update(domain_params)
        format.html { redirect_to @domain, notice: 'Domain was successfully updated.' }
        format.json { render :show, status: :ok, location: @domain }
      else
        format.html { render :edit }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @domain.destroy
    respond_to do |format|
      format.html { redirect_to domains_url, notice: 'Domain was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_domain
    if request.subdomain.empty?
      @domain = Domain.find(params[:id])
    else
      @domain = Domain.find_by!(subdomain: request.subdomain)
    end
  end

  def domain_params
    params.require(:domain).permit(:title, :subdomain, :description)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @domains = Domain.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def home_url
    root_url(subdomain: '')
  end
end

app/views/contents/_form.html.erb
<%= form_for(@content) do |f| %>
  <% if @content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
      <% @content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :domain_id %><br>
    <%= f.collection_select :domain_id, Domain.all, :id, :subdomain %>
  </div>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :slug %><br>
    <%= f.text_field :slug %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contents/edit.html.erb
<h1>Editing Content</h1>

<%= render 'form' %>

<%= link_to 'Show', @content %> |
<%= link_to 'Back', contents_path %>

app/views/contents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Contents</h1>
<h3><%= link_to '+ New Content', new_content_path %></h3>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Slug</th>
      <th>Domain</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contents.each do |content| %>
      <tr>
        <td><%= content.title %></td>
        <td><%= content.slug %></td>
        <td><%= content.domain.subdomain %></td>
        <td><%= link_to 'Show', content_url(content) %></td>
        <td><%= link_to 'Edit', edit_content_path(content) %></td>
        <td><%= link_to 'Destroy', content, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/contents/new.html.erb
<h1>New Content</h1>

<%= render 'form' %>

<%= link_to 'Back', contents_path %>

app/views/contents/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @content.title %></h1>
<h2><%= @content.slug %></h2>

<p>
  <strong>Domain:</strong>
  <%= @content.domain.subdomain %>
</p>

<p>
  <strong>Description:</strong>
  <%= @content.description %>
</p>

app/views/domains/_form.html.erb
<%= form_for(@domain) do |f| %>
  <% if @domain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@domain.errors.count, "error") %> prohibited this domain from being saved:</h2>

      <ul>
      <% @domain.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :subdomain %><br>
    <%= f.text_field :subdomain %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/domains/edit.html.erb
<h1>Editing Domain</h1>

<%= render 'form' %>

<%= link_to 'Show', @domain %> |
<%= link_to 'Back', domains_path %>

app/views/domains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Domains</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Subdomain</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @domains.each do |domain| %>
      <tr>
        <td><%= domain.title %></td>
        <td><%= domain.subdomain %></td>
        <td><%= domain.description %></td>
        <td><%= link_to 'Show', domain %></td>
        <td><%= link_to 'Edit', edit_domain_path(domain) %></td>
        <td><%= link_to 'Destroy', domain, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Domain', new_domain_path %>

app/views/domains/new.html.erb
<h1>New Domain</h1>

<%= render 'form' %>

<%= link_to 'Back', domains_path %>

app/views/domains/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @domain.subdomain.upcase %></h1>
<h2><%= @domain.title %></h2>

<div>
  <% if @domain.has_page_domain? %>
    <%= @domain.description %>
  <% else %>
    <ul>
      <% @domain.contents.each do |content| %>
        <li><%= link_to content.title, content_path(content) %></li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/home/index.html.erb
<h1>Domínios</h1>

<ul>
  <% @domains.each do |domain| %>
    <li>
      <%= link_to domain.title, root_url(subdomain: domain.subdomain) %>
    </li>
    <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MultitenancyExample</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="menu-principal container">
    <%= link_to 'Home', home_url %> |
    <%= link_to 'Contents', contents_url %>  
  </nav>

  <main id="main" class="container">
    <%= yield %>
  </main>
</body>
</html>